config/routes.rb
Rails.application.routes.draw do
  get 'user_steps/client'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :customer do
      root 'dashboard#show'
      resources :shipments
      resources :clients
      resources :reports
      resources :products
      resources :billings
      resources :quotes do
        collection do
          get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
          get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
          get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
          get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
          get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
          get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

          get :tariffs
        end
      end
    end

    namespace :admin do
      resources :settings,  only: [:set_language] do
        collection do
          get 'set_language/:id/:language', action: :set_language, as: 'set_language'
        end
      end
      resources :criteria
      resources :tariffs_imports, only: [:create]
      resources :rate_surcharges
      resources :rates, only: %i[edit update destroy]
      resources :tariffs do
        collection do
          post 'import'
          get 'filter_freight_types/:service_mode', action: :filter_freight_types, as: 'filter_freight_types'
          get 'filter_carriers/:service_mode', action: :filter_carriers, as: 'filter_carriers'
          get 'port_code/:port_id', action: :port_code, as: 'port_code'
        end
      end
      resources :agents do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'filter_address/:address_id', action: :filter_address, as: 'filter_address'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_document
          get :edit_document
          get :show_document
          delete :destroy_document
          post :add_document
          patch :update_document
          put :update_document

        end
      end
      resources :client_documents
      resources :products
      resources :access_roles do
        collection do
          get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
          get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
          #get 'add_permission/:id/:access_id/:module_id', action: :add_permission, as: 'add_permission'
        end
      end
      resources :roles do
        member do
          get :assign
        end
      end
      resources :containers
      resources :charges do
        member do
          delete :destroy_charge
        end
      end
      resources :shipments
      resources :suppliers do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact
        end
      end
      resources :clients do
        collection do
          post 'filter', action: :filter, as: 'filter'

          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'set_column/:column', action: :set_column, as: 'set_column'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_sender
          get :edit_sender
          get :show_sender
          delete :destroy_sender
          post :add_sender
          patch :update_sender

          get :new_client_product
          get :edit_client_product
          get :show_client_product
          delete :destroy_client_product
          post :add_client_product
          patch :update_client_product
          put :update_client_product

          get :new_client_document
          get :edit_client_document
          get :show_client_document
          get :download_client_document
          delete :destroy_client_document
          post :add_client_document
          patch :update_client_document
          put :update_client_document

          get :import_csv_file

        end
        resources :addresses
        resources :phones
        resources :contacts
        resources :senders
      end
      resources :quotes, except: %i[new create edit update] do
        member do
          get :authorize
        end
      end
      resources :middlemen do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
        end
      end
      resources :users
      resources :services
      resources :packaging_types
      resources :taxes, except: :show
      resources :ports
      resources :documents
      root 'dashboard#show'
    end

    root 'home#index'
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    resources :user_steps
  end
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
      format: false
end

app/controllers/admin/clients_controller.rb
module Admin
  # Creates the CRUD for the clients.
  class ClientsController < Admin::ApplicationController
    include Utils::Search
    skip_before_action :verify_authenticity_token
    before_action :add_index_breadcrumb_metronic, only: %i[show new edit]
    before_action :set_client, only: %i[edit show destroy update new_address show_address
                                        edit_address update_address destroy_address
                                        new_phone show_phone destroy_phone edit_phone
                                        update_phone]
    before_action :set_readonly, only: %i[show]
    before_action :set_client_for_product, only: %i[new_client_product edit_client_product update_client_product]
    before_action :set_client_for_document, only: %i[new_client_document edit_client_document update_client_document]
    before_action :set_client_for_contact, only: %i[new_contact show_contact edit_contact destroy_contact]
    before_action :set_address, only: %i[show_address edit_address update_address destroy_address]
    before_action :set_phone, only: %i[show_phone edit_phone update_phone destroy_phone]
    before_action :set_contact, only: %i[show_contact edit_contact update_contact destroy_contact]
    before_action :set_sender, only: %i[show_sender edit_sender update_sender destroy_sender]
    before_action :set_client_product, only: %i[edit_client_product update_client_product destroy_client_product]
    before_action :set_client_document, only: %i[edit_client_document update_client_document destroy_client_document download_client_document]

    load_and_authorize_resource

    def index
      add_breadcrumbs_metronic I18n.translate('activerecord.models.client.other').html_safe
      set_default_columns
      @column_names = get_columns
      @all_columns = @clients.get_all_columns_names
      respond_to do |format|
        format.html
        # format.json { render json: ClientsDatatable.new(view_context)}
      end
    end

    def show
      @addresses = @client.addresses.page params[:page]
      @contacts = @client.contacts.order('principal DESC').page params[:page]
      @senders = @client.senders.order('name DESC').page params[:page]
      @phones = phone_list(@client, @contacts, @senders)
      @products = @client.client_products.page params[:page]
      @documents = @client.client_documents.page params[:page]
      dashboard
      add_breadcrumbs_metronic @client.name.to_s.html_safe
      respond_to do |format|
        format.js { render 'show.js.erb' }
        format.html
        format.pdf {
          render pdf: "Client No. #{@client.id}",
                 disposition: 'inline',
                 page_size: 'A4',
                 template: 'admin/clients/report.html.slim',
                 layout: 'template',
                 orientation: 'Landscape',
                 lowquality: true,
                 zoom: 1,
                 dpi: 75
        }
      end
    end

    def dashboard
      @serie = [
        { name: 'Embarque FS-001', data: 20 },
        { name: 'Embarque FS-002', data: 15 },
        { name: 'Embarque FS-003', data: 35 },
        { name: 'Embarque FS-004', data: 10 },
        { name: 'Embarque FS-005', data: 20 },
      ]
      User.default_timezone = :utc
      @user_date = User.group_by_day(:created_at).count
      @options = {
        title: 'Properties Growth',
        subtitle: 'Grouped Per Day',
        xtitle: 'Day',
        ytitle: 'Properties',
        stacked: true,
        height: 200
      }
    end

    def new
      @client = Client.new
      @client.addresses.build
      2.times do
        @client.phones.build
      end
      @client.contacts.build.phones.build
      add_breadcrumbs_metronic I18n.translate('views.admin.clients.new.subtitle').html_safe
    end

    def edit; end

    def create
      @client = Client.new(client_params)
      if @client.save
        flash[:success] = I18n.translate('controllers.clients.create')
        redirect_to admin_clients_path
      else
        render :new
      end
    end

    def update
      if @client.update(client_params)
        @response = t('controllers.clients.update')
        respond_to do |format|
          format.js
        end
      else
        render :show
      end
    end

    def destroy
      @client.destroy
      flash[:error] = I18n.translate('controllers.clients.destroy')
      redirect_to admin_clients_path
    end

    def new_address
      @is_contact = params[:is_contact]
      @address = Address.new
    end

    def show_address; end

    def add_address
      @is_contact = false
      @create = false
      @address = Address.new(address_params)
      @client = Client.find(@address.addressable_id)
      respond_to do |format|
        if @address.save
          @create = true
          @is_contact = params[:is_contact]
          @addresses = @client.addresses.page params[:page]
          @response = t('controllers.addresses.create')
          format.js { render layout: false, content_type: 'text/javascript' }
          format.html {}
        else
          puts @address.errors.messages
        end
      end
    end

    def edit_address; end

    def update_address
      @update = false
      respond_to do |format|
        if @address.update(address_params)
          @addresses = @client.addresses.page params[:page]
          @update = true
          @response = t('controllers.addresses.update')
          format.js { render layout: false, content_type: 'text/javascript' }
          format.html {}
        end
      end
    end

    def destroy_address
      @address.destroy
      @addresses = @client.addresses.page params[:page]
      @response  = t('controllers.addresses.destroy')
      respond_to do |format|
        format.html {}
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    end

    def clone_address(address)
      cloneAddress = Address.new
      cloneAddress.name = address.name
      cloneAddress.street = address.street
      cloneAddress.interior_number = address.interior_number
      cloneAddress.outdoor_number = address.outdoor_number
      cloneAddress.colony = address.colony
      cloneAddress.city = address.city
      cloneAddress.country = address.country
      cloneAddress.zip_code = address.zip_code
      cloneAddress.state_id = address.state_id
      cloneAddress.address_type_ids = address.address_type_ids
      cloneAddress.principal = address.principal
      cloneAddress
    end

    def new_phone
      @phone = Phone.new
    end

    def add_phone
      @phone = Phone.new(phone_params)
      @client = Client.find(@phone.phoneable_id)
      respond_to do |format|
        if @phone.save
          @contacts = @client.contacts.order('principal DESC').page params[:page]
          @senders = @client.senders
          @phones = phone_list(@client, @contacts, @senders)
          @response = t('controllers.phones.create')
          format.js { render layout: false, content_type: 'text/javascript' }
        else
          format.js { render :new_phone, content_type: 'text/javascript' }
        end
      end
    end

    def show_phone; end

    def edit_phone; end

    def update_phone
      @client = Client.find(@phone.phoneable_id)
      respond_to do |format|
        if @phone.update(phone_params)
          @contacts = @client.contacts.order('principal DESC').page params[:page]
          @senders = @client.senders
          @phones = phone_list(@client, @contacts, @senders)
          @response = t('controllers.phones.update')
          format.js { render layout: false, content_type: 'text/javascript' }
        else
          format.js { render :edit_phone, content_type: 'text/javascript' }
        end
      end
    end

    def destroy_phone
      @client = Client.find(@phone.phoneable_id)
      @contacts = @client.contacts.order('principal DESC').page params[:page]
      @phone.destroy
      @phones = phone_list(@client, @contacts, @senders)
      @response  = t('controllers.phones.destroy')
      respond_to do |format|
        format.html {}
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    end

    def new_contact
      @contact = Contact.new
      @contact.addresses.build
      @contact.phones.build
      @contacts = @client.contacts.order('principal DESC').page params[:page]
      @button = t('views.shared.buttons.save')
    end

    def add_contact
      @create = false
      @contact = Contact.new(contact_params)
      @client = Client.find(@contact.contactable_id)
      if !params[:address][:id].blank?
        address = Address.find(params[:address][:id])
        @contact.addresses << clone_address(address)
      end
      respond_to do |format|
        if @contact.save
          @create = true
          rol = Role.find_by_name('Cliente')
          password = Devise.friendly_token.first(8)
          user = User.create(username: @contact.name.mentionable, password: password, email: @contact.email, role_id: rol.id)
          puts "\n\n\nPassword:"
          puts "Password: #{password}"
          RegistrationMailer.welcome_email(user, password).deliver
          @response = t('controllers.contacts.create')
          @contacts = @client.contacts.order('principal DESC').page params[:page]
          format.js { render layout: false, content_type: 'text/javascript' }
          format.html {}
        end
      end
    end

    def show_contact; end

    def edit_contact
      @contact.phones.build if @contact.phones.blank?
      @contacts = @client.contacts.order('principal DESC').page params[:page]
      @button = t('views.shared.buttons.update')
    end

    def update_contact
      @update = false
      @client = Client.find(@contact.contactable_id)
      respond_to do |format|
        if @contact.update(contact_params)
          @contacts = @client.contacts.order('principal DESC').page params[:page]
          @update = true
          @response = t('controllers.contacts.update')

app/views/admin/clients/_addresses_information.html.slim
#address_list
  = render 'admin/clients/addresses/accordion_addresses'

app/views/admin/clients/_client.html.slim
.row
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.input :name, placeholder: t('activerecord.attributes.client.name'), input_html: { class: 'form-control-sm', title: t('views.admin.clients.shared.text.step1.instructions.name'), data: { toggle: "tooltip", placement: "top" } }
      .fv-plugins-message-container
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.input :rfc, placeholder: t('activerecord.attributes.client.rfc'), input_html: { class: 'form-control-sm' }
      .fv-plugins-message-container
.row
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.input :website, placeholder: t('activerecord.attributes.client.website'), input_html: { class: 'form-control-sm' }
      .fv-plugins-message-container
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.association :currency, label_method: :code, prompt: t('views.shared.prompt.currency'), input_html: { class: 'form-control-sm' }
      .fv-plugins-message-container
- count = 0
#phones
  = f.simple_fields_for :phones do |phone|
    - count = count + 1
    = render 'phone_fields', f: phone, attribute: "attribute_#{count}", code: "code_#{count}", type_phone: "type_phone_#{count}", number: "number_#{count}", input_number: "input_number_#{count}"
.row
  .col-xl-4.col-sm-12
    .form-group.fv-plugins-icon-container
      .custom-control.custom-switch
        = f.input_field :advanced_parameters, label: false, as: :boolean, class: 'custom-control-input'
        = f.label :advanced_parameters, class: 'custom-control-label'
  .col-xl-4.col-sm-12
    .form-group.fv-plugins-icon-container
      .custom-control.custom-switch
        = f.input_field :has_credit, label: false, as: :boolean, class: 'custom-control-input'
        = f.label :has_credit, class: 'custom-control-label'

.row.hide-element#advanced_parameters
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.association :parent_entity, prompt: t('views.admin.clients.shared.prompt.parent_entity'), input_html: { class: 'form-control-sm' }
      .fv-plugins-message-container
  .col-xl-6.col-sm-12
    .form-group.fv-plugins-icon-container
      = f.association :middleman, prompt: t('views.shared.prompt.middleman'), input_html: { class: 'form-control-sm' }
      .fv-plugins-message-container

javascript:
    jQuery(document).ready(function () {
        const checked_has_credit = document.getElementById('client_has_credit').checked;
        if (checked_has_credit) {
            $("#accordionCredit").removeClass("hide-element");
        } else {
            $("#accordionCredit").addClass("hide-element");
        }

        const checked_advanced_parameters = document.getElementById('client_advanced_parameters').checked;
        if (checked_advanced_parameters) {
            $("#advanced_parameters").removeClass("hide-element");
        } else {
            $("#advanced_parameters").addClass("hide-element");
            $('#client_parent_entity_id').val('');
            $('#client_middleman_id').val('');
        }

        // client_has_credit
        $("#client_advanced_parameters").on("click", function () {
            console.log("click");
            const chk = document.getElementById('client_advanced_parameters').checked;
            console.log(chk);
            if (chk) {
                $("#advanced_parameters").removeClass("hide-element");
            } else {
                $("#advanced_parameters").addClass("hide-element");
                $('#client_parent_entity_id').val('');
                $('#client_middleman_id').val('');
            }
        });

        $("#client_has_credit").on("click", function () {
            const chk = document.getElementById('client_has_credit').checked;
            console.log(chk);
            if (chk) {
                $("#accordionCredit").removeClass("hide-element");
            } else {
                $("#accordionCredit").addClass("hide-element");
            }
        });
    });

app/views/admin/clients/_filter_form.html.slim
= form_with url: filter_admin_clients_path, remote: true do |f|
  // service_mode
  .modal-body
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.shipment.mode_transportation')
      .col-9
        = f.select :service_mode, Shipment.service_modes.keys.map { |w| [w.humanize, w] }, { prompt: t('views.shared.prompt.service_mode') }, { class: 'form-control form-control-sm' }
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.shipment.freight_type')
      .col-9
        = f.select :freight_type, ModeTransportation.all.map { |w| [w.code, w.id] }, { prompt: t('views.shared.prompt.freight_type') }, { class: 'form-control form-control-sm' }
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.shipment.incoterm')
      .col-9
        = f.select :incoterm, Incoterm.all.map { |w| [w.code, w.id] }, { prompt: t('views.shared.prompt.incoterm') }, { class: 'form-control form-control-sm' }
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.client.payment_term')
      .col-9
        = f.select :payment_term, PaymentTerm.all.map { |w| [w.description, w.id] }, { prompt: t('views.shared.prompt.payment_term') }, { class: 'form-control form-control-sm' }
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.client.annual_international_freight_shipments')
      .col-9
        = f.select :annual_international_freight_shipments, Client.annual_international_freight_shipments.keys.map { |w| [w.humanize, w] }, { prompt: 'Select a option' }, { class: 'form-control form-control-sm' }
    .form-group.row
      label.col-3.col-form-label = t('activerecord.attributes.client.status')
      .col-9
        = f.select :status, Client.statuses.keys.map { |w| [w.humanize, w] }, { prompt: t('views.shared.prompt.status') }, { class: 'form-control form-control-sm' }
  .modal-footer
    button.btn.btn-secondary data-dismiss="modal" type="button" = t('views.shared.buttons.cancel')
    = submit_tag t('views.shared.buttons.apply'), class: 'btn btn-primary'

app/views/admin/clients/_phone_fields.html.slim
.nested-fields
  = f.hidden_field :id
  = f.hidden_field :phoneable_id
  = f.hidden_field :phoneable_type, value: 'Client'
  = f.hidden_field :_destroy
  = f.hidden_field :code, class: "#{code}"
  = f.hidden_field :type_phone, class: "#{type_phone}"
  .row
    .col-xl-4.col-sm-12
      .form-group.fv-plugins-icon-container
        = f.label :number, class: "#{number}"
        = f.input :number, label: false, placeholder: t('activerecord.attributes.phone.number'), input_html: { class: "form-control-sm #{input_number}" }
    .col-xl-4.col-sm-12 id="#{attribute}"
      .form-group.fv-plugins-icon-container
        = f.input :extension, placeholder: t('activerecord.attributes.phone.extension'), input_html: { class: 'form-control-sm' }
    .col-xl-4.col-sm-12
      .form-group.fv-plugins-icon-container.mt-8
        .custom-control.custom-switch
          = f.input_field :principal, label: false, as: :boolean, class: 'custom-control-input'
          = f.label :principal, class: 'custom-control-label'


javascript:
    $(document).ready(function () {
        const input_phone_number = $(".input_number_1");
        const input_mobile_number = $(".input_number_2");
        $(".intl-tel-input").css("width", "100%");
        input_phone_number.intlTelInput({
            formatOnInit: true,
            separateDialCode: false,
            placeholderNumberType: 'MOBILE',
            initialCountry: "mx",
            nationalMode: false,
            hiddenInput: "full",
            preferredCountries: ["mx", "us"],
        });

        input_mobile_number.intlTelInput({
            formatOnInit: true,
            separateDialCode: false,
            placeholderNumberType: 'MOBILE',
            initialCountry: "mx",
            nationalMode: false,
            hiddenInput: "full",
            preferredCountries: ["mx", "us"],
        });

        console.log("#{t('activerecord.attributes.phone.mobile_number')}");

        $("#attribute_2").addClass('hide-element');
        $(".type_phone_1").val("permanent");
        $(".type_phone_2").val("mobile");
        $(".number_2").text("#{t('activerecord.attributes.phone.mobile_number')}");

        $("#client_phones_attributes_0_principal").on("click", function () {
            console.log("click principal 0");
            const chk = document.getElementById('client_phones_attributes_0_principal').checked;
            console.log(chk);
            if (chk) {
                $("#client_phones_attributes_1_principal").attr("disabled", true);
            } else {
                $("#client_phones_attributes_1_principal").removeAttr("disabled");
            }
        });

        $("#client_phones_attributes_1_principal").on("click", function () {
            console.log("click principal 1");
            const chk = document.getElementById('client_phones_attributes_1_principal').checked;
            console.log(chk);
            if (chk) {
                $("#client_phones_attributes_0_principal").attr("disabled", true);
            } else {
                $("#client_phones_attributes_0_principal").removeAttr("disabled");
            }
        });
    });

app/views/admin/clients/_phones_information.html.slim
.card.card-custom.card-stretch
  .card-header.py-3
    .card-title.align-items-start.flex-column
      h3.card-label.font-weight-bolder.text-dark = t('views.admin.clients.show.tabs.phone.subtitle')
    .card-toolbar
      = link_to t('views.shared.buttons.new'), new_phone_admin_client_path(@client.id), class: 'btn btn-success', 'data-remote': true
  .card-body
    #phone_list
      = render 'admin/clients/phones/collection'

app/views/admin/clients/_senders.html.slim
.dataTables_wrapper.dt-bootstrap4.no-footer#kt_datatable_wrapper
  .container
    .row
      .col-sm-12
        table.table.table-separate.table-head-custom.table-checkable.dataTable.no-footer.dtr-inline#kt_datatable role="grid" aria-describedby="kt_datatable_info" style="width: 905px;"
          thead
            tr.text-left role="row"
              th class="sorting_asc" tabindex="0" aria-controls="kt_datatable" rowspan="1" colspan="1" style="min-width: 200px;" aria-sort="ascending" aria-label="Name: activate to sort column descending" = t('activerecord.attributes.sender.name')
              th class="sorting_asc" tabindex="0" aria-controls="kt_datatable" rowspan="1" colspan="1" style="min-width: 150px;" aria-sort="ascending" aria-label="Email: activate to sort column descending" = t('activerecord.attributes.sender.contact')          
              th class="sorting_asc" tabindex="0" aria-controls="kt_datatable" rowspan="1" colspan="1" style="min-width: 200px;" aria-sort="ascending" aria-label="Name: activate to sort column descending" = t('activerecord.attributes.sender.email')
              th class="sorting_asc" tabindex="0" aria-controls="kt_datatable" rowspan="1" colspan="1" style="min-width: 150px;" aria-sort="ascending" aria-label="Email: activate to sort column descending" = t('activerecord.attributes.sender.rfc')
              th class="sorting_asc" tabindex="0" aria-controls="kt_datatable" rowspan="1" colspan="1" style="min-width: 150px;" aria-sort="ascending" aria-label="Actions: activate to sort column descending" = t('views.admin.clients.index.collections.actions')
          tbody
            - @senders.each do |sender|
              tr role="row"
                td = sender.name
                td = sender.contact       
                td = sender.email
                td = sender.rfc                         
                td nowrap="nowrap"
                  = link_to show_sender_admin_client_path(id: @client.id, sender_id: sender.id), class: 'btn btn-icon btn-light btn-hover-primary btn-sm mr-3', remote: true do
                    span.svg-icon.svg-icon-md.svg-icon-primary
                      i.la.la-info-circle
                  = link_to edit_sender_admin_client_path(id: @client.id, sender_id: sender.id) , class: 'btn btn-icon btn-light btn-hover-primary btn-sm mr-3', remote: true do
                    span.svg-icon.svg-icon-md.svg-icon-primary
                      i.la.la-edit
                  = link_to destroy_sender_admin_client_path(id: @client.id, sender_id: sender.id), class: 'btn btn-icon btn-light btn-hover-primary btn-sm mr-3', remote: true, method: :delete, data: {confirm: 'Are you sure?'} do
                    span.svg-icon.svg-icon-md.svg-icon-primary
                      i.la.la-trash

app/views/admin/clients/add_client_document.js.erb
<% if @client_document.errors.empty? %>
  $("#document_form").html("<%= j render :partial => 'admin/clients/client_documents/collection' %>");
  $("#paginator").html("<%= escape_javascript(paginate(@documents, remote: true)) %>");
  toastr.success("<%= escape_javascript(@response) %>");
<% else %>
<% end %>

app/views/admin/clients/destroy_sender.js.erb
$("#senders").html("<%= j render partial: 'admin/clients/senders/collection' %>");
$("#paginator").html("<%= escape_javascript(paginate(@senders, remote: true)) %>");
toastr.error("<%= escape_javascript(@response) %>");

app/views/admin/clients/destroy_sender_backup.js.erb
$("#senders_list").html("<%= j render partial: 'admin/clients/senders'  %>");

app/views/admin/clients/index.html.slim
= render 'shared/subheader', custom_button: true, export_button: true, back_button: false, back_button_route: '', new_button: true, new_button_route: new_admin_client_path, quote_button: false, shipment_button: false, rate_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom
      .card-body     
        = render 'collection'
    = render 'shared/manage_columns_form'