config/routes.rb
Rails.application.routes.draw do
  get 'user_steps/client'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :customer do
      root 'dashboard#show'
      resources :shipments
      resources :clients
      resources :reports
      resources :products
      resources :billings
      resources :quotes do
        collection do
          get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
          get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
          get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
          get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
          get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
          get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

          get :tariffs
        end
      end
    end

    namespace :admin do
      resources :settings,  only: [:set_language] do
        collection do
          get 'set_language/:id/:language', action: :set_language, as: 'set_language'
        end
      end
      resources :criteria
      resources :tariffs_imports, only: [:create]
      resources :rate_surcharges
      resources :rates, only: %i[edit update destroy]
      resources :tariffs do
        collection do
          post 'import'
          get 'filter_freight_types/:service_mode', action: :filter_freight_types, as: 'filter_freight_types'
          get 'filter_carriers/:service_mode', action: :filter_carriers, as: 'filter_carriers'
          get 'port_code/:port_id', action: :port_code, as: 'port_code'
        end
      end
      resources :agents do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'filter_address/:address_id', action: :filter_address, as: 'filter_address'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_document
          get :edit_document
          get :show_document
          delete :destroy_document
          post :add_document
          patch :update_document
          put :update_document

        end
      end
      resources :client_documents
      resources :products
      resources :access_roles do
        collection do
          get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
          get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
          #get 'add_permission/:id/:access_id/:module_id', action: :add_permission, as: 'add_permission'
        end
      end
      resources :roles do
        member do
          get :assign
        end
      end
      resources :containers
      resources :charges do
        member do
          delete :destroy_charge
        end
      end
      resources :shipments
      resources :suppliers do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact
        end
      end
      resources :clients do
        collection do
          post 'filter', action: :filter, as: 'filter'

          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'set_column/:column', action: :set_column, as: 'set_column'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_sender
          get :edit_sender
          get :show_sender
          delete :destroy_sender
          post :add_sender
          patch :update_sender

          get :new_client_product
          get :edit_client_product
          get :show_client_product
          delete :destroy_client_product
          post :add_client_product
          patch :update_client_product
          put :update_client_product

          get :new_client_document
          get :edit_client_document
          get :show_client_document
          get :download_client_document
          delete :destroy_client_document
          post :add_client_document
          patch :update_client_document
          put :update_client_document

          get :import_csv_file

        end
        resources :addresses
        resources :phones
        resources :contacts
        resources :senders
      end
      resources :quotes, except: %i[new create edit update] do
        member do
          get :authorize
        end
      end
      resources :middlemen do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
        end
      end
      resources :users
      resources :services
      resources :packaging_types
      resources :taxes, except: :show
      resources :ports
      resources :documents
      root 'dashboard#show'
    end

    root 'home#index'
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    resources :user_steps
  end
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
      format: false
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :bigint           not null, primary key
#  deleted_at :datetime
#  name       :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_roles_on_deleted_at  (deleted_at)
#  index_roles_on_slug        (slug)
#
class Role < ApplicationRecord
  extend FriendlyId

  acts_as_paranoid
  audited

  friendly_id :name, use: :slugged

  has_many :users, inverse_of: :role
  has_many :access_roles, inverse_of: :role
  has_many :accesses, through: :access_roles, inverse_of: :roles

  accepts_nested_attributes_for :access_roles

  validates :name, presence: true
end

app/controllers/admin/roles_controller.rb
module Admin
  # Creates the CRUD for the roles
  class RolesController < Admin::ApplicationController
    before_action :set_role, only: %i[edit show update destroy assign]
    before_action :add_index_breadcrumb_metronic, only: %i[show new edit assign]

    load_and_authorize_resource

    def index
      @roles = Role.all.order(:name)
      add_breadcrumbs_metronic I18n.translate('activerecord.models.role.other')
    end

    def show
      add_breadcrumbs_metronic @role.name
    end

    def new
      add_breadcrumbs_metronic I18n.translate('views.admin.roles.new.subtitle').html_safe
      @role = Role.new
    end

    def create
      @role = Role.new(role_params)
      if @role.save
        flash[:success] = 'Role successfully created'
        redirect_to admin_roles_path
      else
        render :new
      end
    end

    def edit
      add_breadcrumbs_metronic "#{t('views.admin.roles.edit.subtitle')} #{@role.name}".html_safe
    end

    def update
      if @role.update(role_params)
        flash[:success] = 'Role successfully updated'
        redirect_to admin_roles_path
      else
        render :edit
      end
    end

    def destroy
      @role.destroy
      flash[:error] = 'Role successfully deleted'
      redirect_to admin_roles_path
    end

    def assign
      add_breadcrumbs_metronic "#{@role.name} - #{t('views.admin.roles.assign.subtitle')}".html_safe
      @access = AccessRole.where(role_id: @role.id)
    end

    private

    def role_params
      params.require(:role).permit(:name)
    end

    def set_role
      @role = Role.friendly.find(params[:id])
    end

    def add_index_breadcrumb_metronic
      add_breadcrumbs_metronic I18n.translate('activerecord.models.role.other').html_safe, admin_roles_path
    end
  end
end

app/views/admin/roles/_collection.html.slim
.dataTables_wrapper.dt-bootstrap4.no-footer#kt_datatable_wrapper
  table.table.table-separate.table-head-custom.collapsed#kt_datatable_general
    thead
      tr
        th = t('activerecord.attributes.role.name')
        th = t('views.shared.tags.actions')
    tbody
      - @roles.each do |role|
        tr
          td
            .d-flex.align-items-center
              .symbol.symbol-50.symbol-light-secondary
                span.symbol-label
                  = role.id
              .ml-3
                span.text-dark-75.font-weight-bold.line-height-sm.d-block.pb-2 = role.name
          td nowrap="nowrap"
            = link_to(edit_admin_role_path(role), class: 'btn btn-sm btn-clean btn-icon', title: t('views.shared.buttons.edit'), data: { toggle: 'tooltip', placement: "top" }) do
              span.svg-icon.svg-icon-md.svg-icon-primary
                i.fas.fa-edit
            = link_to assign_admin_role_path(role), class: 'btn btn-sm btn-clean btn-icon', title: t('activerecord.models.access_role.other'), data: { toggle: 'tooltip', placement: "top" } do
              span.svg-icon.svg-icon-md.svg-icon-primary
                i.fas.fa-lock
            = link_to({action: :destroy, id: role.id}, class: "btn btn-sm btn-clean btn-icon", title: t('views.shared.buttons.destroy'), method: :delete, data: { toggle: 'tooltip', placement: "top", confirm: 'Are you okay?' }) do
              span.svg-icon.svg-icon-md.svg-icon-primary
                i.fas.fa-trash
javascript:
    jQuery(document).ready(function () {
        KTDatatablesGeneral.init();
    });

app/views/admin/roles/_form.html.erb
<%= simple_form_for [:admin, @role] do |f| %>
  <div class="form-group row">
    <div class="col-sm-12 col-lg-6">
      <%= f.input :name, placeholder: t('activerecord.attributes.container.name'), readonly: permissions %>
    </div>
  </div>
  <div class="row">
    <div class="col-4"></div>
    <div class="col-8 text-right">
      <%= f.submit button_primary, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/roles/_show.html.erb
<div class="form-group row">
  <div class="col-sm-12 col-lg-6">
    <%= label :role, :name %>
    <%= text_field :role, :name, placeholder: t('activerecord.attributes.container.name'), readonly: permissions, value: @role.name, class: 'form-control' %>
  </div>
</div>
<% if permissions %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th></th>
        <%= t('activerecord.models.access.other') %>
        <% prepare_hash %>
        <% @access_order = Access.all.order("id ASC") %>
        <% @access_order.each do |access| %>
          <th>
            <%= t("views.admin.access.#{access.name.downcase}") %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% access = @access_order.all.pluck(:id) %>
      <% SystemModule.all.each do |sm| %>
        <tr>
          <input type="hidden" name="role_id" class= 'role_id' value= <%= @role.id %> >
          <th>
            <%= t("activerecord.models.#{squish(sm.name)}.other") %>
          </th>
          <td>
            <label class="checkbox checkbox-inline">
              <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[0])) %>  value= '<%= access[0] %> : <%= sm.id  %>' >
              <span></span>
            </label>
          </td>
          <td>
            <label class="checkbox checkbox-inline">
              <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[1])) %>  value= '<%= access[1] %> : <%= sm.id  %>' >
              <span></span>
            </label>
          </td>
          <td>
            <label class="checkbox checkbox-inline">
              <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[2])) %>  value= '<%= access[2] %> : <%= sm.id  %>' >
              <span></span>
            </label>
          </td>
          <td>
            <label class="checkbox checkbox-inline">
              <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[3])) %>  value= '<%= access[3] %> : <%= sm.id  %>' >
              <span></span>
            </label>
          </td>
          <td>
            <label class="checkbox checkbox-inline">
              <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[4])) %>  value= '<%= access[4] %> : <%= sm.id  %>' >
              <span></span>
            </label>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<script>
    $('document').ready(function() {

        $(':checkbox').on('change', function() {
            var $this = $(this);
            var ids = $this.val();
            var id_array = ids.split(':');
            var system_module_id = id_array[1];
            var access_id = id_array[0];
            var role_id = $('.role_id').val();
            var url;
            console.log(system_module_id.trim());
            console.log(access_id.trim());
            console.log(role_id.trim());

            if (this.checked) {
                url = "/admin/access_roles/add_access/" + role_id.trim() + "/" + access_id.trim() + "/" + system_module_id.trim();
            } else {
                url = "/admin/access_roles/remove_access/" + role_id.trim() + "/" + access_id.trim() + "/" + system_module_id.trim();
            }
            console.log(url);
            $.ajax({
                url: url,
                type: "get",
                success: function (data) {
                    if (data.type == 'success') {
                        toastr.success(data.response)
                    } else {
                        toastr.error(data.response)
                    }
                },
                error: function (data) {
                    console.log(data);
                }
            })
        });
    });
</script>

app/views/admin/roles/assign.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: true, back_button_route: admin_roles_path, new_button: false, new_button_route: '', shipment_button: false, rate_button: false, quote_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom
      .card-body
        = render 'admin/roles/show', permissions: true, button_primary: t('views.shared.buttons.update')

app/views/admin/roles/edit.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: true, back_button_route: admin_roles_path, new_button: false, new_button_route: '', shipment_button: false, rate_button: false, quote_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom
      .card-body
        = render 'form', permissions: false, button_primary: t('views.shared.buttons.update')

app/views/admin/roles/index.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: false, back_button_route: '', new_button: true, new_button_route: new_admin_role_path, quote_button: false, shipment_button: false, rate_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom
      .card-body
        = render 'admin/roles/collection'

app/views/admin/roles/new.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: true, back_button_route: admin_roles_path, new_button: false, new_button_route: '', quote_button: false, shipment_button: false, rate_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom
      .card-body
        = render 'form', permissions: false, button_primary: t('views.shared.buttons.save')