config/routes.rb
Rails.application.routes.draw do
  get 'user_steps/client'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :customer do
      root 'dashboard#show'
      resources :shipments
      resources :clients
      resources :reports
      resources :products
      resources :billings
      resources :quotes do
        collection do
          get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
          get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
          get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
          get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
          get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
          get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

          get :tariffs
        end
      end
    end

    namespace :admin do
      resources :settings,  only: [:set_language] do
        collection do
          get 'set_language/:id/:language', action: :set_language, as: 'set_language'
        end
      end
      resources :criteria
      resources :tariffs_imports, only: [:create]
      resources :rate_surcharges
      resources :rates, only: %i[edit update destroy]
      resources :tariffs do
        collection do
          post 'import'
          get 'filter_freight_types/:service_mode', action: :filter_freight_types, as: 'filter_freight_types'
          get 'filter_carriers/:service_mode', action: :filter_carriers, as: 'filter_carriers'
          get 'port_code/:port_id', action: :port_code, as: 'port_code'
        end
      end
      resources :agents do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'filter_address/:address_id', action: :filter_address, as: 'filter_address'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_document
          get :edit_document
          get :show_document
          delete :destroy_document
          post :add_document
          patch :update_document
          put :update_document

        end
      end
      resources :client_documents
      resources :products
      resources :access_roles do
        collection do
          get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
          get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
          #get 'add_permission/:id/:access_id/:module_id', action: :add_permission, as: 'add_permission'
        end
      end
      resources :roles do
        member do
          get :assign
        end
      end
      resources :containers
      resources :charges do
        member do
          delete :destroy_charge
        end
      end
      resources :shipments
      resources :suppliers do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact
        end
      end
      resources :clients do
        collection do
          post 'filter', action: :filter, as: 'filter'

          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'set_column/:column', action: :set_column, as: 'set_column'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_sender
          get :edit_sender
          get :show_sender
          delete :destroy_sender
          post :add_sender
          patch :update_sender

          get :new_client_product
          get :edit_client_product
          get :show_client_product
          delete :destroy_client_product
          post :add_client_product
          patch :update_client_product
          put :update_client_product

          get :new_client_document
          get :edit_client_document
          get :show_client_document
          get :download_client_document
          delete :destroy_client_document
          post :add_client_document
          patch :update_client_document
          put :update_client_document

          get :import_csv_file

        end
        resources :addresses
        resources :phones
        resources :contacts
        resources :senders
      end
      resources :quotes, except: %i[new create edit update] do
        member do
          get :authorize
        end
      end
      resources :middlemen do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
        end
      end
      resources :users
      resources :services
      resources :packaging_types
      resources :taxes, except: :show
      resources :ports
      resources :documents
      root 'dashboard#show'
    end

    root 'home#index'
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    resources :user_steps
  end
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
      format: false
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                                     :bigint           not null, primary key
#  advanced_parameters                    :boolean
#  annual_international_freight_shipments :bigint
#  authorized_credit                      :boolean          default(FALSE)
#  credit_limit                           :decimal(10, 4)   default(0.0)
#  deleted_at                             :datetime
#  has_credit                             :boolean          default(FALSE)
#  inactive                               :boolean          default(FALSE)
#  name                                   :string
#  rfc                                    :string
#  slug                                   :string
#  status                                 :bigint           default("pending")
#  website                                :string
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  cfdi_id                                :bigint
#  currency_id                            :bigint
#  middleman_id                           :bigint
#  parent_entity_id                       :bigint
#  payment_method_id                      :bigint
#  payment_term_id                        :bigint
#  way_pay_id                             :bigint
#
# Indexes
#
#  index_clients_on_cfdi_id            (cfdi_id)
#  index_clients_on_currency_id        (currency_id)
#  index_clients_on_deleted_at         (deleted_at)
#  index_clients_on_middleman_id       (middleman_id)
#  index_clients_on_parent_entity_id   (parent_entity_id)
#  index_clients_on_payment_method_id  (payment_method_id)
#  index_clients_on_payment_term_id    (payment_term_id)
#  index_clients_on_slug               (slug)
#  index_clients_on_way_pay_id         (way_pay_id)
#
# Foreign Keys
#
#  fk_rails_...  (cfdi_id => cfdis.id)
#  fk_rails_...  (currency_id => currencies.id)
#  fk_rails_...  (middleman_id => middlemen.id)
#  fk_rails_...  (parent_entity_id => clients.id)
#  fk_rails_...  (payment_method_id => payment_methods.id)
#  fk_rails_...  (payment_term_id => payment_terms.id)
#  fk_rails_...  (way_pay_id => way_pays.id)
#
class Client < ApplicationRecord
  include Addressable
  include Contactable
  include Noteable
  include Phoneable
  include Senderable
  include InformationDetail
  include Filterable
  extend FriendlyId

  acts_as_paranoid
  audited

  friendly_id :name, use: :slugged

  has_one :bank_account, inverse_of: :client
  has_one_attached :contract
  has_one_attached :logo

  has_many :client_products, inverse_of: :client
  has_many :client_documents, inverse_of: :client
  has_many :products, through: :client_products, inverse_of: :clients
  has_many :quotes, inverse_of: :client
  has_many :shipments, inverse_of: :client
  has_many :shipment_entities, inverse_of: :client

  belongs_to :cfdi, inverse_of: :clients, optional: true
  belongs_to :currency, inverse_of: :clients
  belongs_to :middleman, inverse_of: :clients, optional: true
  belongs_to :payment_method, inverse_of: :clients, optional: true
  belongs_to :payment_term, inverse_of: :clients, optional: true
  belongs_to :parent_entity, class_name: 'Client', inverse_of: :parent_entity, optional: true
  belongs_to :way_pay, inverse_of: :clients, optional: true

  validates :name, presence: true
  # validates :middleman, presence: true, if: :advanced_parameters?
  # validates :parent_entity, presence: true, if: :advanced_parameters?

  enum status: %i[pending authorized denied]
  enum annual_international_freight_shipments: %i[500 100 25 none_first none_ship]


  def advanced_parameters?
    advanced_parameters == true
  end

  def self.get_columns_names(incluir_columnas)
    columnas = Client.column_names
    excluir_columnas = columnas - incluir_columnas
    columnas - excluir_columnas
  end

  def self.get_all_columns_names
    excluir_columnas = %W[id parent_entity_id advanced_parameters slug created_at updated_at deleted_at]
    columnas = Client.column_names
    columnas - excluir_columnas
  end
end

app/models/sender.rb
# == Schema Information
#
# Table name: senders
#
#  id              :bigint           not null, primary key
#  address         :string
#  contact         :string
#  deleted_at      :datetime
#  email           :string
#  name            :string
#  phone           :string
#  rfc             :string
#  senderable_type :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  senderable_id   :bigint
#
# Indexes
#
#  index_senders_on_deleted_at                         (deleted_at)
#  index_senders_on_senderable_type_and_senderable_id  (senderable_type,senderable_id)
#
class Sender < ApplicationRecord
  include Phoneable
  audited

  has_one_attached :logo

  belongs_to :senderable, polymorphic: true

  has_many :sender_sender_types, inverse_of: :sender, dependent: :destroy
  has_many :sender_types, through: :sender_sender_types, inverse_of: :senders

  validates :name, presence: true

  def principal_phone?
    principal_phone = false
    phones.each do |phone|
      principal_phone = true if phone.principal == true
    end
    principal_phone
  end

  # function that obtains the data from the contact's main telephone number
  def principal_phone
    principal_phone = Phone.new
    phones.each do |phone|
      principal_phone = phone if phone.principal == true
    end
    principal_phone
  end

  # function that gets the main phone number of the principal contact.
  def phone
    principal_phone.number.blank? ? '' : principal_phone.number.to_s.strip
  end

  # function that obtains the number with extension of the main telephone of the principal contact.
  def phone_with_extension
    extension + phone
  end

  def extension
    principal_phone.extension.blank? ? '' : principal_phone.extension
  end

  # function that obtains the country code number of the main telephone of the principal contact.
  def phone_with_country_code
    country_code + phone
  end

  def country_code
    principal_phone.code.blank? ? '' : "#{principal_phone.code} "
  end
end

app/models/sender_type.rb
# == Schema Information
#
# Table name: sender_types
#
#  id         :bigint           not null, primary key
#  deleted_at :datetime
#  inactive   :boolean          default(FALSE)
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_sender_types_on_deleted_at  (deleted_at)
#
class SenderType < ApplicationRecord
  audited

  has_many :sender_sender_types, inverse_of: :sender_type
  has_many :senders, through: :sender_sender_types, inverse_of: :sender_types
end

app/controllers/customer/clients_controller.rb
module Customer
  class ClientsController < Customer::ApplicationController
    def index

    end
  end
end

app/views/admin/clients/senders/_collection.html.slim
- unless @senders.blank?
  - @senders.each_slice(3) do |group|
    .row.mb-2
      - group.each do |sender|
        .col-xl-4
          = render 'admin/clients/senders/sender', sender: sender
  .row
    .col-xl-12#paginator
      = paginate @senders, remote: true
- else
  .not-register
    = "#{t('views.shared.text.not_records')} de #{t('activerecord.models.sender.other')}."

app/views/admin/clients/senders/_form.html.slim
= simple_form_for @sender, url: url_for(controller: 'admin/clients', action: action_controller), remote: true do |f|
  = f.hidden_field :senderable_type, value: 'Client'
  = f.hidden_field :senderable_id, value: @client.id
  = hidden_field_tag :sender_id, @sender.id
  = hidden_field_tag :id
  = submit_tag '', class: "btn btn-primary", id: 'btnSubmitSender', style: "display: none;"
  .row
    .col-xl-6
      = f.input :name, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.name')
    .col-xl-6
      = f.input :rfc, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.rfc')
  .row.mt-2
    .col-xl-6
      = f.input :email, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.email')
    .col-xl-6
      = f.input :contact, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.contact')
  .row.mt-2
    .col-xl-6
      = f.label :sender_type_ids
      = f.select :sender_type_ids, options_for_select(SenderType.all.collect { |st| [st.name, st.id] }, @sender.sender_type_ids), {}, { class: 'form-control', multiple: true }
  = f.simple_fields_for :phones do |phone|
    = render 'admin/clients/senders/phone_fields', f: phone, phoneable_type: 'Sender'
  .row.mr-2
    .col-xl-12
      = f.input :address, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.address')
javascript:
    $(function () {
        $('#btn_submit_modal').click(function () {
          $('#senders_information_tab_6').trigger("click");
        });
        $('#sender_sender_type_ids').selectpicker();
        $("#btnCancelSender").click(function () {
            $("#sender_form").hide();
            $("#senders").show();
        });
        $("#btnSender").click(function () {
            $('#btnSubmitSender').trigger("click");
        });
    });

app/views/admin/clients/senders/_new.html.slim
.card.card-custom.card-stretch#sender_form
  .card-header.py-3
    .card-title.align-items-start.flex-column
      h3.card-label.font-weight-bolder.text-dark = t('views.admin.senders.new.title')
    .card-toolbar.align-items
      button.mr-2 id="btnCancelSender" class="btn btn-danger" = t('views.shared.buttons.cancel')
      button id="btnSender" class="btn btn-success" = @button
  .card-body
    = render 'admin/clients/senders/form', action_controller: action_controller, action: action, title: t('views.admin.senders.new.title'), button: t('views.shared.buttons.save')

app/views/admin/clients/senders/_phone_fields.html.slim
.nested-fields
  = f.hidden_field :id
  = f.hidden_field :phoneable_id
  = f.hidden_field :code
  = f.hidden_field :phoneable_type, value: phoneable_type
  = f.hidden_field :principal, value: true
  .row
    .col-xl-6
      .form-group.fv-plugins-icon-container
        = f.input :type_phone, collection: Phone.type_phones, placeholder: t('activerecord.attributes.phone.type_phone'), prompt: t('views.admin.clients.shared.prompt.type_phone'), input_html: { class: 'form-control-sm type_phone_sender' }
    .col-xl-6.col-sm-12.hide-element#country-code-sender
      = f.label :mobile_number
      = f.input :mobile_number, placeholder: t('activerecord.attributes.phone.number'), input_html: { class: 'country-code-tel-sender form-control-sm ' }, label: false
    .col-xl-3.hide-element#phone-code-sender
      .form-group.fv-plugins-icon-container
        = f.input :number, placeholder: t('activerecord.attributes.phone.number'), input_html: { class: 'extension-code-tel-sender form-control-sm ' }
    .col-xl-3.hide-element#extension-code-sender
      .form-group.fv-plugins-icon-container
        = f.input :extension, placeholder: t('activerecord.attributes.phone.extension'), input_html: { class: 'extension-code-number-sender form-control-sm ' }
javascript:
    $(document).ready(function () {
        const input = $(".country-code-tel-sender");
        $('.type_phone_sender').on('change', function () {
            if ($('.type_phone_sender').val() == '') {
                $('#country-code-sender').addClass('hide-element');
                $('#extension-code-sender').addClass('hide-element');
                $('#phone-code-sender').addClass('hide-element');
                $('.extension-code-tel-sender').val('');
                $('.extension-code-number-sender').val('');
                $(".country-code-tel-sender").val('');
            } else if ($('.type_phone_sender').val() == 'permanent') {
                if (!$("#country-code-sender").hasClass('hide-element')) {
                    $('#country-code-sender').addClass('hide-element');
                    $(".country-code-tel-sender").val('');
                }
                $('#extension-code-sender').removeClass('hide-element');
                $('#phone-code-sender').removeClass('hide-element');
            } else {
                input.intlTelInput({
                    formatOnInit: true,
                    separateDialCode: false,
                    placeholderNumberType: 'MOBILE',
                    initialCountry: "mx",
                    nationalMode: false,
                    hiddenInput: "full",
                });
                if (!$("#extension-code-sender").hasClass('hide-element')) {
                    $('#extension-code-sender').addClass('hide-element');
                    $('#phone-code-sender').addClass('hide-element');
                    $('.extension-code-tel-sender').val('');
                    $('.extension-code-number-sender').val('');
                }
                $('#country-code-sender').removeClass('hide-element')
            }
        });

        $("#new_sender").submit(function () {
            let countryData = $('#sender_phones_attributes_0_mobile_number').intlTelInput("getSelectedCountryData");
            let countryCode = countryData.dialCode
            $('#sender_phones_attributes_0_code').val(countryCode);
        });
    });

app/views/admin/clients/senders/_sender.html.slim
.card.card-custom.gutter-b.card-stretch.card-rounded
  .card-body.pt-4.d-flex.flex-column.justify-content-between
    /-- begin::Toolbar--
    .d-flex.justify-content-end
      .dropdown.dropdown-inline data-toggle="tooltip" title="Quick actions" data-placement="left"
        a class="btn btn-clean btn-hover-light-primary btn-sm btn-icon" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          i.fas.fa-ellipsis-h
        .dropdown-menu.dropdown-menu-md.dropdown-menu-right
          ul.navi.navi-hover
            li.navi-item
              = link_to edit_sender_admin_client_path(id: @client.id, sender_id: sender.id), class: 'navi-link', remote: true do
                span.navi-icon
                  i.fas.fa-edit
                span.navi-text = t('views.shared.buttons.edit')
            li.navi-item
              = link_to destroy_sender_admin_client_path(id: @client.id, sender_id: sender.id), class: 'navi-link', remote: true, method: :delete, data: { confirm: 'Are you sure?' } do
                span.navi-icon
                  i.fas.fa-trash
                span.navi-text = t('views.shared.buttons.destroy')
    /-- end::Toolbar--
    /--begin::User--
    .d-flex.align-items-center.mb-7
      .flex-shrink-0.mr-4.mt-lg-0.mt-3
        - if sender.logo.attached?
          .symbol.symbol-75
            = image_tag(sender.logo.service_url)
        - else
          .symbol.symbol-lg-75
            = image_tag('sender.png')
      .d-flex.flex-column
        = link_to show_sender_admin_client_path(id: @client.id, sender_id: sender.id), class: 'text-dark font-weight-bold text-hover-primary font-size-h4 mb-0', remote: true do
          = sender.name.truncate(15)
    /--end::User--
    /--begin::Desc--
    p.mb-7
    /--end::Desc--
    /--begin::Info--
    .mb-7
      .d-flex.justify-content-between.align-items-center
        span.text-dark-75.font-weight-bolder.mr-2 = "#{t('views.admin.clients.index.abbreviate.email')}:"
        = link_to sender.email.truncate(15), "#", class: "text-muted text-hover-primary"
      .d-flex.justify-content-between.align-items-center.my-1
        span.text-dark-75.font-weight-bolder.mr-2 = "#{t('views.admin.clients.index.abbreviate.phone')}:"
        label.text-muted.text-hover-primary
          - if sender.extension != ""
            = sender.phone_with_extension
          - elsif sender.country_code != ""
            = sender.phone_with_country_code
    /--end::Info--
    a href="#" class="btn btn-block btn-sm btn-light-warning font-weight-bolder text-uppercase py-4" write message

app/views/admin/clients/senders/_sender_fields.html.slim
.row
    .col-xl-12
        .form-group.fv-plugins-icon-container
            = f.label :sender_type_ids
                = f.select :sender_type_ids, options_for_select(SenderType.all.collect {|st| [st.name, st.id]}, @client.sender_ids), {}, { class: 'form-control selectpicker', multiple: true, data: { 'live-search': "true" } }
 

app/views/admin/clients/senders/_show.html.slim
.row
  .col-xl-6
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.name')}:"
      label.col-xl-9.col-lg-9.col-form-label = @sender.name
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.rfc')}:"
      label.col-xl-9.col-lg-9.col-form-label = @sender.rfc
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.email')}:"
      label.col-xl-9.col-lg-9.col-form-label = @sender.email
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.models.phone.one')}:"
      label.col-xl-9.col-lg-9.col-form-label
        - if @sender.extension != ""
          = @sender.phone_with_extension
        - elsif @sender.country_code != ""
          = @sender.phone_with_country_code
  .col-xl-6
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.contact')}:"
      label.col-xl-9.col-lg-9.col-form-label = @sender.contact
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.address')}:"
      label.col-xl-9.col-lg-9.col-form-label = @sender.address
    .row
      label.col-xl-3.col-lg-3.col-form-label.text-right
        b = "#{t('activerecord.attributes.sender.sender_type_ids')}:"
      label.col-xl-9.col-lg-9.col-form-label
        - sender_types = ""
        - @sender.sender_type_ids.each do |id|
          - sender_type = SenderType.find id
          - sender_types += sender_type.name + " "
        = sender_types