config/routes.rb
Rails.application.routes.draw do
  get 'user_steps/client'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :customer do
      root 'dashboard#show'
      resources :shipments
      resources :clients
      resources :reports
      resources :products
      resources :billings
      resources :quotes do
        collection do
          get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
          get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
          get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
          get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
          get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
          get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

          get :tariffs
        end
      end
    end

    namespace :admin do
      resources :settings,  only: [:set_language] do
        collection do
          get 'set_language/:id/:language', action: :set_language, as: 'set_language'
        end
      end
      resources :criteria
      resources :tariffs_imports, only: [:create]
      resources :rate_surcharges
      resources :rates, only: %i[edit update destroy]
      resources :tariffs do
        collection do
          post 'import'
          get 'filter_freight_types/:service_mode', action: :filter_freight_types, as: 'filter_freight_types'
          get 'filter_carriers/:service_mode', action: :filter_carriers, as: 'filter_carriers'
          get 'port_code/:port_id', action: :port_code, as: 'port_code'
        end
      end
      resources :agents do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'filter_address/:address_id', action: :filter_address, as: 'filter_address'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_document
          get :edit_document
          get :show_document
          delete :destroy_document
          post :add_document
          patch :update_document
          put :update_document

        end
      end
      resources :client_documents
      resources :products
      resources :access_roles do
        collection do
          get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
          get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
          #get 'add_permission/:id/:access_id/:module_id', action: :add_permission, as: 'add_permission'
        end
      end
      resources :roles do
        member do
          get :assign
        end
      end
      resources :containers
      resources :charges do
        member do
          delete :destroy_charge
        end
      end
      resources :shipments
      resources :suppliers do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact
        end
      end
      resources :clients do
        collection do
          post 'filter', action: :filter, as: 'filter'

          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
          get 'set_column/:column', action: :set_column, as: 'set_column'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
          put :update_contact
          post :update_contact

          get :new_sender
          get :edit_sender
          get :show_sender
          delete :destroy_sender
          post :add_sender
          patch :update_sender

          get :new_client_product
          get :edit_client_product
          get :show_client_product
          delete :destroy_client_product
          post :add_client_product
          patch :update_client_product
          put :update_client_product

          get :new_client_document
          get :edit_client_document
          get :show_client_document
          get :download_client_document
          delete :destroy_client_document
          post :add_client_document
          patch :update_client_document
          put :update_client_document

          get :import_csv_file

        end
        resources :addresses
        resources :phones
        resources :contacts
        resources :senders
      end
      resources :quotes, except: %i[new create edit update] do
        member do
          get :authorize
        end
      end
      resources :middlemen do
        collection do
          get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
        end
        member do
          get :update_readonly

          get :new_address
          get :edit_address
          get :show_address
          delete :destroy_address
          post :add_address
          patch :update_address

          get :new_phone
          get :edit_phone
          get :show_phone
          delete :destroy_phone
          post :add_phone
          patch :update_phone

          get :new_contact
          get :edit_contact
          get :show_contact
          delete :destroy_contact
          post :add_contact
          patch :update_contact
        end
      end
      resources :users
      resources :services
      resources :packaging_types
      resources :taxes, except: :show
      resources :ports
      resources :documents
      root 'dashboard#show'
    end

    root 'home#index'
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    resources :user_steps
  end
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
      format: false
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id                  :bigint           not null, primary key
#  authorized          :boolean          default(FALSE)
#  danger_item         :boolean          default(FALSE)
#  declared_value      :decimal(10, 4)   default(0.0)
#  deleted_at          :datetime
#  description         :text
#  expired_at          :datetime
#  free_day_of_delay   :integer
#  frequency           :bigint
#  guarantee_letter    :boolean          default(FALSE)
#  is_active_shipment  :boolean          default(FALSE)
#  number              :string
#  operation_type      :integer
#  quoted_at           :datetime
#  service_mode        :bigint
#  service_type        :string
#  slug                :string
#  status              :bigint           default("open")
#  total_pieces        :decimal(10, 4)   default(0.0)
#  total_volume        :decimal(20, 4)   default(0.0)
#  total_weight        :decimal(10, 4)   default(0.0)
#  total_weight_volume :decimal(20, 4)   default(0.0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  client_id           :bigint
#  employee_id         :bigint
#  freight_type_id     :bigint
#  incoterm_id         :bigint
#  organization_id     :bigint
#  payment_term_id     :bigint
#  rate_id             :bigint
#  salesman_id         :bigint
#
# Indexes
#
#  index_quotes_on_client_id        (client_id)
#  index_quotes_on_deleted_at       (deleted_at)
#  index_quotes_on_employee_id      (employee_id)
#  index_quotes_on_freight_type_id  (freight_type_id)
#  index_quotes_on_incoterm_id      (incoterm_id)
#  index_quotes_on_organization_id  (organization_id)
#  index_quotes_on_payment_term_id  (payment_term_id)
#  index_quotes_on_rate_id          (rate_id)
#  index_quotes_on_salesman_id      (salesman_id)
#  index_quotes_on_slug             (slug)
#
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id)
#  fk_rails_...  (employee_id => employees.id)
#  fk_rails_...  (freight_type_id => mode_transportations.id)
#  fk_rails_...  (incoterm_id => incoterms.id)
#  fk_rails_...  (organization_id => organizations.id)
#  fk_rails_...  (payment_term_id => payment_terms.id)
#  fk_rails_...  (rate_id => rates.id)
#  fk_rails_...  (salesman_id => employees.id)
#
class Quote < ApplicationRecord
  include Chargeable
  include Filterable

  extend FriendlyId
  acts_as_paranoid
  audited
  friendly_id :number, use: :slugged

  paginates_per 4

  belongs_to :client, inverse_of: :quotes, optional: true
  belongs_to :employee, inverse_of: :quotes, optional: true
  belongs_to :freight_type, class_name: 'ModeTransportation', inverse_of: :quotes, optional: true
  belongs_to :incoterm, inverse_of: :quotes, optional: true
  belongs_to :organization, inverse_of: :quotes
  belongs_to :payment_term, inverse_of: :quotes, optional: true
  belongs_to :rate, inverse_of: :quotes, optional: true
  belongs_to :salesman, class_name: 'Employee', inverse_of: :quotes, optional: true

  has_many :quote_units, inverse_of: :quote, dependent: :destroy

  has_many :quote_optional_services, inverse_of: :quote, dependent: :destroy
  has_many :optional_services, through: :quote_optional_services

  has_one :shipment, inverse_of: :quote
  has_one :origin_route, inverse_of: :quote
  has_one :destiny_route, inverse_of: :quote

  enum frequency: %i[diary weekly biweekly monthly yearly]
  enum operation_type: %i[national export import]
  enum service_mode: %i[aerial land maritime]
  enum type_service: %i[door_door door_port port_port port_door]
  enum status: %i[open closed confirmed declined]

  accepts_nested_attributes_for :destiny_route
  accepts_nested_attributes_for :origin_route
  accepts_nested_attributes_for :quote_units
  accepts_nested_attributes_for :quote_optional_services

  after_save :generate_number

  scope :filter_by_service_mode, lambda { |servide_mode|
    where('quotes.service_mode = ?', servide_mode)
  }

  def generate_number
    update_column(:number, "FS-#{1000 + id}")
  end

  def total_costs_charge
    charges_cost = Charge.where('type_charge = ? AND chargeable_id = ?', 1, id)
    total_charges_cost = 0
    charges_cost.each do |cc|
      total_charges_cost += cc.total
    end
    total_charges_cost
  end

  def total_incomes_charge
    charges_cost = Charge.where('type_charge = ? AND chargeable_id = ?', 0, id)
    total_charges_cost = 0
    charges_cost.each do |cc|
      total_charges_cost += cc.total
    end
    total_charges_cost
  end

  def editable?
    is_active_shipment
  end
end

app/controllers/admin/quotes_controller.rb
module Admin
  # Quotes Controller
  class QuotesController < Admin::ApplicationController
    before_action :set_quote, only: %i[show destroy authorize]
    before_action :add_index_breadcrumb_metronic, only: %i[show]

    load_and_authorize_resource

    respond_to :html, :js, only: [:index]

    def index
      add_breadcrumbs_metronic I18n.translate('activerecord.models.quote.other')
      # @filter = params.slice(:service_mode) unless params[:service_mode].blank?
      # @filter = @filter[:service_mode] unless params[:service_mode].blank?
      @quotes = Quote.filter(params.slice(:service_mode, :status)).where('authorized = false').page(params[:page])
      respond_with(@quotes)
    end

    def show
      @expenses = 0
      @incomes = 0
      @profit = 0
      @charges = @quote.charges
      @charges.each do |charge|
        @expenses += charge.total.to_f if charge.type_charge == 'expense'
        @incomes += charge.total.to_f if charge.type_charge == 'income'
        @profit = @incomes.to_f - @expenses.to_f
      end
      add_breadcrumbs_metronic @quote.number.html_safe
    end

    def destroy
      @quote.destroy
      flash[:error] = 'Quote successfully deleted'
      redirect_to admin_quotes_path
    end

    def authorize
      shipment = initialize_shipment(@quote)
      shipment.quote_id = @quote.id
      shipment.shipment_units = initialize_shipment_units(@quote.quote_units)
      shipment.collection_route = initialize_collection_routes(@quote.origin_route)
      shipment.delivery_route = initialize_delivery_route(@quote.destiny_route)
      if shipment.save
        @quote.update(authorized: true)
        flash[:success] = t('controllers.quotes.authorize')
        redirect_to admin_quotes_path
      else
        flash[:error] = 'Review the data'
      end
    end

    private

    def set_quote
      @quote = Quote.friendly.find(params[:id])
    end

    def initialize_shipment(quote)
      Shipment.new(quote.attributes.except!('quoted_at', 'rate_id', 'expired_at', 'payment_term_id',
                                            'organization_id', 'service_type', 'total_weight_volume',
                                            'is_active_shipment', 'authorized', 'id', 'status'))
    end

    def initialize_shipment_units(quote_units)
      shipment_units = []
      quote_units.each do |quote_unit|
        shipment_unit = ShipmentUnit.new(quote_unit.attributes.except('quote_id', 'service_id'))
        shipment_units << shipment_unit
      end
      shipment_units
    end

    def initialize_collection_routes(quote_origin)
      CollectionRoute.new(quote_origin.attributes.except('quote_id'))
    end

    def initialize_delivery_route(quote_destiny)
      DeliveryRoute.new(quote_destiny.attributes.except('quote_id'))
    end

    def add_index_breadcrumb_metronic
      add_breadcrumbs_metronic I18n.translate('activerecord.models.quote.other').html_safe, admin_quotes_path
    end
  end
end

app/views/admin/quotes/_collection.html.slim
.row
  .col-xl-6
    = link_to admin_quotes_path(service_mode: 1), class: 'btn btn-filter btn-sm mr-1', remote: true do
      i.fas.fa-truck.fa-2x style="color: #fff"
    = link_to admin_quotes_path(service_mode: 0), class: 'btn btn-filter btn-sm mr-1', remote: true do
      i.fas.fa-plane.fa-2x style="color: #fff"
    = link_to admin_quotes_path(service_mode: 2), class: 'btn btn-filter btn-sm mr-1', remote: true do
      i.fas.fa-ship.fa-2x style="color: #fff"
    = link_to admin_quotes_path, class: 'btn btn-filter btn-sm mr-1' do
      i.fas.fa-broom.fa-2x style="color: #fff"
.mt-5#quotes
  - unless @quotes.blank?
    = render @quotes
  - else
    .not-register
      = "#{t('views.shared.text.not_records')} de #{t('activerecord.models.quote.other')}."

- if @quotes.current_page == @quotes.total_pages
- else
  p.d-flex.justify-content-center id="view-more"
    = link_to(t('views.shared.buttons.load_more'), url_for(page: @quotes.current_page + 1), class: 'btn btn-info', remote: true)

javascript:
    $(document).ready(function () {
        $(window).scroll(function () {
            const url = $('#view-more a').attr('href');
            if (url && $(window).scrollTop() > $(document).height() - $(window).height() - 50) {
                $('#view-more').html('Obteniendo más posts');
                return $.getScript(url);
            }
        });
        return $(window).scroll();
    });

app/views/admin/quotes/_quote.html.slim
.row.align-items-center style="background-color: #f5f5f5"
  .col-lg-2.text-center
    - if quote.rate.tariff.carrier.logo.attached?
      = image_tag(rate.tariff.carrier.logo.service_url, width: 80, height: 80)
    - else
      i.fas.fa-3x.fa-truck
    h4.font-weight-boldest.order-1.order-md-2 = quote.rate.tariff.carrier.name
  .col-lg-2.text-center
    = flag_icon(quote.origin_route.origin_port.country.code.downcase, squared: true, class: 'fa-2x mt-1')
    h4.font-weight-bold = quote.origin_route.origin_port.port_identifier
  .col-lg-2.text-center
    // = "#{quote.rate.transite_time} #{t('views.shared.text.days')}"
    = render 'table', quote: quote
  .col-lg-2.text-center
    = flag_icon(quote.destiny_route.destiny_port.country.code.downcase, squared: true, class: 'fa-2x mt-1')
    h4.font-weight-bold = quote.destiny_route.destiny_port.port_identifier
  .col-lg-2.text-center
    h3.font-weight-bold = number_to_currency(quote.rate.minimal_cost, unit: '$', format: '%u %n')
    = t('activerecord.attributes.rate.minimal_cost')
  .col-lg-2.text-center
    h3.font-weight-bold = number_to_currency(quote.rate.minimal_cost, unit: '$', format: '%u %n')
    | Total
.row style="background-color: #005cb9"
  .col-xl-8
    = link_to t('views.shared.buttons.show').upcase, [:admin, quote], style: 'color: white !important;', class: 'font-weight-bold'
  .col-xl-4.text-right
    span style="color: white !important;" = "#{t('activerecord.attributes.rate.transite_time')}: #{quote.rate.transite_time} #{t('views.shared.text.days')}"
.mb-4

app/views/admin/quotes/_table.html.erb
<ul class="progress-meter">
  <li class="progress-step progress-complete">
    <span></span>
    <label for="" style="font-size: 8px">.</label>
  </li>
  <li class="progress-step">
    <span></span>
    <label for="" style="font-size: 8px">.</label>
  </li>
  <li class="progress-step">
    <span></span>
    <label for="" style="font-size: 8px">.</label>
  </li>
</ul>

app/views/admin/quotes/_tabs.html.slim
ul.nav.nav-tabs id="myTab" role="tablist"
  li.nav-item
    a.nav-link.active id="all-tab" data-toggle="tab" href="#all"
      span.nav-text
        = "#{t('views.admin.quotes.index.tabs.all')} (#{@quotes.size})"
  li.nav-item
    a.nav-link id="open-tab" data-toggle="tab" href="#open"
      span.nav-text
        = "#{t('views.admin.quotes.index.tabs.open')} (#{@quotes.size})"
  li.nav-item
    a.nav-link id="closed-tab" data-toggle="tab" href="#closed"
      span.nav-text
        = "#{t('views.admin.quotes.index.tabs.closed')} (#{@quotes.size})"
  li.nav-item
    a.nav-link id="confirmed-tab" data-toggle="tab" href="#confirmed"
      span.nav-text
        = "#{t('views.admin.quotes.index.tabs.confirmed')} (#{@quotes.size})"
  li.nav-item
    a.nav-link id="declined-tab" data-toggle="tab" href="#declined"
      span.nav-text
        = "#{t('views.admin.quotes.index.tabs.declined')} (#{@quotes.size})"
javascript:
    $(document).ready(function () {
        $("#all-tab").click(function (e) {
            console.log("all");
        });
        $("#open-tab").click(function () {
            console.log("open");
        });
        $("#closed-tab").click(function () {
            console.log("closed");
        });
        $("#declined-tab").click(function () {
            console.log("declined");
        });
        $("#confirmed-tab").click(function () {
            console.log("confirmed");
        });
    });

app/views/admin/quotes/index.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: false, back_button_route: '', new_button: false, new_button_route: new_admin_tariff_path, quote_button: false, shipment_button: false, rate_button: false
.d-flex.flex-column-fluid
  .container
    .row
      .col-xl-12
        .card.card-custom.gutter-b
          .card-body
            = render 'collection'

app/views/admin/quotes/show.html.slim
= render 'shared/subheader', custom_button: false, export_button: false, back_button: true, back_button_route: admin_quotes_path, new_button: false, new_button_route: '', quote_button: false, shipment_button: false, rate_button: false
.d-flex.flex-column-fluid
  .container
    .card.card-custom.gutter-bs
      .card-header.card-header-tabs-line
        .card-toolbar
          ul.nav.nav-tabs.nav-tabs-space-lg.nav-tabs-line.nav-tabs-bold.nav-tabs-line-3x role="tablist"
            li.nav-item.mr-3
              a.nav-link.active data-toggle="tab" href="#kt_apps_quote_view_tab_1"
                span.nav-icon.mr-2
                  span.svg-icon.mr-3
                    i.fas.fa-calculator.fa6-aside-icon
                span.nav-text.font-weight-bold = t('views.admin.quotes.show.tabs.general.title')
            li.nav-item.mr-3
              a.nav-link data-toggle="tab" href="#kt_apps_quote_view_tab_2"
                span.nav-icon.mr-2
                  span.svg-icon.mr-3
                    i.fas.fa-boxes.fa6-aside-icon
                span.nav-text.font-weight-bold = t('views.admin.quotes.show.tabs.products.title')
      .card-body.px-0
        .tab-content.pt-5
          .tab-pane.active#kt_apps_quote_view_tab_1 role="tabpanel"
            .container
              form.form
                .row
                  .col-lg-12
                    .container-fluid.d-flex.align-items-center.justify-content-between.flex-wrap.flex-sm-nowrap
                      .d-flex.align-items-center.flex-wrap.mr-1
                        .d-flex.align-items-baseline.flex-wrap.mr-5
                          h5.text-dark.font-weight-bold.my-1.mr-5.mb-4 = t('views.admin.quotes.show.tabs.general.subtitle1')
                      div style = "display: flex; justify-content: flex-end"
                        = link_to authorize_admin_quote_path(@quote.id), class: 'btn btn btn-info' do
                          = t('views.shared.buttons.authorize')
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.number')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid  value = @quote.number
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote_route.type_service')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid  value = t("enums.quote.type_service.#{@quote.service_type}")
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.operation_type')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid  value = t("enums.quote.operation_type.#{@quote.operation_type}")
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.incoterm')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid  value = @quote.incoterm.code
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.organization')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = @quote.organization.name
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.salesman')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = (@quote.salesman.blank? ? '' : @quote.salesman.name)
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.quoted_at')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value= (@quote.quoted_at.blank? ? '' : @quote.quoted_at.strftime("%m/%d/%Y %R"))
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.expired_at')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value= (@quote.expired_at.blank? ? '' : @quote.expired_at.strftime("%m/%d/%Y %R"))
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.service.service_mode')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = t("enums.quote.service_mode.#{@quote.service_mode}")
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.transportation_modality')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = @quote.freight_type.code
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.frequency')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value =  @quote.frequency
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.free_day_of_delay')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = @quote.free_day_of_delay
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.declared_value')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = @quote.declared_value
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.col-form-label.text-right = t('activerecord.attributes.quote.description')
                    .col-lg-9.col-xl-6
                      input.form-control.form-control-lg.form-control-solid value = @quote.description
                .form-group.row
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.text-right.col-form-label = t("activerecord.attributes.quote.danger_item")
                    .col-lg-9.col-xl-6
                      = check_box_tag :danger_item, 'yes', @quote.danger_item, disabled: true
                  .d-flex.flex-row.flex-root
                    label.col-xl-3.col-lg-3.text-right.col-form-label = t("activerecord.attributes.quote.guarantee_letter")
                    .col-lg-9.col-xl-6
                      = check_box_tag :guarantee_letter, 'yes', @quote.guarantee_letter, disabled: true

          .tab-pane#kt_apps_quote_view_tab_2 role="tabpanel"
            .container
              .row
                .col-sm-12
                  table.table.table-separate.table-head-custom.collapsed#kt_datatable_products
                    thead
                      tr
                        th.pl-0.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.description')
                        th.pl-0.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.packaging_type')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.pieces')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.length')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.height')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.width')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.weight')
                        th.text-right.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.volume')
                    tbody
                      - unless @quote.quote_units.blank?
                        - @quote.quote_units.each do |shipment_detail|
                          tr.font-weight-boldest
                            td.pl-0.pt-7 = shipment_detail.product.name
                            td.pl-0.pt-7 = shipment_detail.packaging_type.code
                            td.text-right.pt-7 = shipment_detail.number_units
                            td.text-right.pt-7 = shipment_detail.length
                            td.text-right.pt-7 = shipment_detail.height
                            td.text-right.pt-7 = shipment_detail.width
                            td.text-right.pt-7 = shipment_detail.weight
                            td.text-right.pt-7 = shipment_detail.volume

              .row
                .col-sm-12
                  .table-responsive
                    table.table
                      thead
                        th.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.total_pieces')
                        th.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.total_weight')
                        th.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.total_volume')
                        th.font-weight-bold.text-muted.text-uppercase = t('activerecord.attributes.shipment_detail.total_weight_volume')
                      tbody
                        tr.font-weight-bolder
                          td.font-weight-bolder = @quote.total_pieces
                          td.font-weight-bolder = @quote.total_weight
                          td.font-weight-bolder = @quote.total_volume
                          td.font-weight-bolder = @quote.total_weight_volume